# Generated by Django 5.1.1 on 2024-10-03 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_create_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_donated',
            field=models.BooleanField(blank=True, default=False, verbose_name='Has Donated?'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_donated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Donated At'),
        ),
    ]
