# Generated by Django 5.1.1 on 2024-10-21 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_disable_donation_notice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='prefetch_question',
            field=models.BooleanField(blank=True, default=False, verbose_name='Prefetch Question'),
        ),
    ]
