# Generated by Django 5.0.3 on 2024-03-20 08:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0002_auto_20240320_1430'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(max_length=64, unique=True)),
                ('source_id_2', models.CharField(max_length=64, unique=True)),
                ('source_id_3', models.CharField(max_length=64, unique=True)),
                ('module', models.CharField(choices=[('en', 'English'), ('math', 'Math')], max_length=4)),
                ('stimulus', models.TextField(default='')),
                ('stem', models.TextField(default='')),
                ('difficulty', models.IntegerField(choices=[(0, 'Unspecified'), (1, 'Easy'), (2, 'Medium'), (3, 'Hard')])),
                ('type', models.CharField(default='', max_length=24)),
                ('explanation', models.TextField(default='')),
                ('raw', models.JSONField(default=None)),
                ('source', models.CharField(default='', max_length=24)),
                ('source_order', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.program')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('explanation', models.TextField(default='')),
                ('correct', models.BooleanField(null=True)),
                ('order', models.PositiveSmallIntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=24, null=True)),
                ('explanation', models.TextField(default='')),
                ('order', models.PositiveSmallIntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question')),
            ],
        ),
    ]
