# Generated by Django 5.0.3 on 2024-03-20 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answerchoice',
            options={'verbose_name': 'Answer Choice'},
        ),
        migrations.AddField(
            model_name='answerchoice',
            name='letter',
            field=models.CharField(default='', max_length=1),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='answerchoice',
            constraint=models.UniqueConstraint(fields=('question', 'order'), name='unique_question_answer_choice_order'),
        ),
        migrations.AddConstraint(
            model_name='answerchoice',
            constraint=models.UniqueConstraint(fields=('question', 'letter'), name='unique_question_answer_choice_letter'),
        ),
    ]
