# Generated by Django 5.0.3 on 2024-03-20 08:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20240320_1430'),
        ('questions', '0002_alter_answerchoice_options_answerchoice_letter_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerchoice',
            name='correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='source_id',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='question',
            name='source_id_2',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='source_id_3',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(condition=models.Q(('source__isnull', False), ('source_id__isnull', False)), fields=('source', 'source_id'), name='unique_question_source_id'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(condition=models.Q(('source__isnull', False), ('source_id_2__isnull', False)), fields=('source', 'source_id_2'), name='unique_question_source_id_2'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(condition=models.Q(('source__isnull', False), ('source_id_3__isnull', False)), fields=('source', 'source_id_3'), name='unique_question_source_id_3'),
        ),
    ]
