# Generated by Django 5.0.3 on 2024-03-20 09:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20240320_1430'),
        ('questions', '0003_alter_answerchoice_correct_alter_question_source_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='source',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='source_id',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.Index(condition=models.Q(('source__isnull', False)), fields=['source'], name='index_question_source'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.Index(condition=models.Q(('source__isnull', False), ('source_id__isnull', False)), fields=['source', 'source_id'], name='index_question_source_id'),
        ),
    ]
