# Generated by Django 5.0.6 on 2024-06-13 01:01

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('questions', '0003_question_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='skill_tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='core.SkillTagged', to='core.SkillTag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questions.question'),
        ),
        migrations.AlterField(
            model_name='answerchoice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_choices', to='questions.question'),
        ),
    ]
