# Generated by Django 5.0.6 on 2024-06-15 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_exam_prevent_copy_exam_retake_exam_retake_after_and_more'),
        ('questions', '0004_question_skill_tags_alter_answer_question_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=6)),
                ('is_correct', models.BooleanField()),
                ('time_taken', models.DurationField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_question_answer_set', to='exams.exam')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_question_answer_set', to='questions.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_answer_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Answer',
            },
        ),
        migrations.CreateModel(
            name='UserQuestionAnswerStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_spr', models.CharField(blank=True, max_length=6, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False)),
                ('is_selected', models.BooleanField(blank=True, default=False)),
                ('answer_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.answerchoice')),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_question_answer_status_set', to='exams.exam')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_question_answer_status_set', to='questions.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_answer_status_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Question Answer Status',
            },
        ),
        migrations.CreateModel(
            name='UserQuestionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_marked_for_review', models.BooleanField(blank=True, default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_question_status_set', to='exams.exam')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_question_status_set', to='questions.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_status_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Question Status',
            },
        ),
        migrations.AddConstraint(
            model_name='userquestionanswer',
            constraint=models.UniqueConstraint(condition=models.Q(('exam__isnull', False)), fields=('user', 'question', 'exam'), name='unique_user_question_answer_exam'),
        ),
        migrations.AddConstraint(
            model_name='userquestionanswerstatus',
            constraint=models.UniqueConstraint(condition=models.Q(('answer_choice__isnull', False)), fields=('user', 'question', 'exam', 'answer_choice'), name='unique_user_question_answer_status_exam'),
        ),
        migrations.AddConstraint(
            model_name='userquestionanswerstatus',
            constraint=models.UniqueConstraint(condition=models.Q(('answer_choice__isnull', True)), fields=('user', 'question', 'exam'), name='unique_user_question_answer_status_exam_spr'),
        ),
        migrations.AddConstraint(
            model_name='userquestionstatus',
            constraint=models.UniqueConstraint(fields=('user', 'question', 'exam'), name='unique_user_question_status_exam'),
        ),
    ]
