# Generated by Django 5.0.6 on 2024-06-15 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_userquestionanswer_userquestionanswerstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='source',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
