# Generated by Django 5.0.6 on 2024-06-19 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_alter_question_source_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquestionstatus',
            name='saw_explanation_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userquestionstatus',
            name='saw_explanation_before',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_set', to='questions.question'),
        ),
        migrations.AlterField(
            model_name='answerchoice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_choice_set', to='questions.question'),
        ),
    ]
