# Generated by Django 5.0.6 on 2024-06-19 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0008_userquestionstatus_saw_explanation_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('E', 'Easy'), ('M', 'Medium'), ('H', 'Hard')], max_length=2, null=True),
        ),
    ]
