# Generated by Django 5.0.6 on 2024-07-02 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0010_remove_answerchoice_unique_question_answer_choice_correct_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userquestionanswer',
            old_name='time_taken',
            new_name='time_given',
        ),
    ]
