# Generated by Django 5.0.6 on 2024-07-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0011_rename_time_taken_userquestionanswer_time_given'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='source_raw_data',
            field=models.JSONField(default=None, null=True),
        ),
    ]
