# Generated by Django 5.0.6 on 2024-07-30 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0013_alter_question_source_alter_question_source_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userquestionanswerstatus',
            options={'verbose_name': 'User Question Answer Status', 'verbose_name_plural': 'User Question Answer Statuses'},
        ),
        migrations.AlterModelOptions(
            name='userquestionstatus',
            options={'verbose_name': 'User Question Status', 'verbose_name_plural': 'User Question Statuses'},
        ),
        migrations.AddField(
            model_name='userquestionstatus',
            name='unmarked_for_review_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userquestionanswer',
            name='answered_at',
            field=models.DateTimeField(),
        ),
    ]
