# Generated by Django 5.0.6 on 2024-08-10 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0015_remove_question_unique_question_source_id_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='question',
            name='index_question_source',
        ),
        migrations.RemoveConstraint(
            model_name='question',
            name='index_question_source_id',
        ),
    ]
