# Generated by Django 5.0.6 on 2024-08-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0016_remove_question_index_question_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='source_raw_data',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
