# Generated by Django 5.0.6 on 2024-09-16 08:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0019_remove_question_unique_question_source_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='uuid',
            field=models.UUIDField(db_index=True, editable=False, null=True),
        ),
    ]
