# Generated by Django 5.0.6 on 2024-09-16 08:35

import uuid
from django.db import migrations


def gen_uuid(apps, schema_editor):
    Question = apps.get_model("questions", "Question")
    for question in Question.objects.filter(uuid=None).only('id', 'uuid'):
        question.uuid = uuid.uuid4()
        question.save(update_fields=["uuid"])

class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0020_question_uuid'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
