# Generated by Django 5.0.6 on 2024-09-17 03:30

from django.db import migrations


def update_null_difficulty_to_empty(apps, schema_editor):
    Question = apps.get_model("questions", "Question")
    Question.objects.filter(difficulty=None).update(difficulty='')


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0022_auto_20240916_1436'),
    ]

    operations = [
        migrations.RunPython(update_null_difficulty_to_empty, reverse_code=migrations.RunPython.noop),
    ]
