# Generated by Django 5.0.6 on 2024-09-17 03:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0023_question_set_null_difficulty_to_empty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(blank=True, choices=[('', 'Unspecified'), ('E', 'Easy'), ('M', 'Medium'), ('H', 'Hard')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='question',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
    ]
