# Generated by Django 5.1.1 on 2024-10-21 19:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0020_exam_module_alter_exam_uuid'),
        ('questions', '0028_alter_question_answer_type_alter_question_difficulty_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userquestionstatus',
            index=models.Index(fields=['user', 'question', 'exam', 'is_marked_for_review'], name='idx_uqs_uqe_mfr'),
        ),
    ]
