# fly.toml app configuration file generated for oneprep on 2024-08-04T19:18:23+06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'oneprep'
primary_region = 'iad'
console_command = '/code/manage.py shell_plus'

swap_size_mb = 512

[build]

[deploy]
  release_command = "python manage.py migrate"

[env]
  PORT = '8000'

  DJANGO_SETTINGS_MODULE = 'config.settings.production'

  DJANGO_ACCOUNT_ALLOW_REGISTRATION = false

  DJANGO_DEBUG = false
  DJANGO_ALLOWED_HOSTS = 'oneprep.fly.dev'

  ENVIRONMENT_NAME = 'production'
  ENVIRONMENT_COLOR = 'orange'

  SENTRY_TRACES_SAMPLE_RATE = 1.0

  Q_LOADER_BASE_PATH = '/data/data/sat'

[mounts]
  source = "oneprep_data"
  destination = "/data"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'
