# Generated by Django 5.0.3 on 2024-03-20 08:30

from django.db import migrations


def add_initial_data(apps, schema_editor):
    Program = apps.get_model('app', 'Program')
    Program.objects.create(pk=0, name="SAT")
    Program.objects.create(pk=1, name="PSAT/NMSQT & PSAT 10")
    Program.objects.create(pk=2,name="PSAT 8/9")


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_initial_data),
    ]
