# Generated by Django 5.0.6 on 2024-06-12 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_alter_examquestion_options_exam_tags'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='source',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='source_id',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='source_order',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.UniqueConstraint(condition=models.Q(('source__isnull', False), ('source_id__isnull', False)), fields=('source', 'source_id'), name='unique_exam_source_id'),
        ),
    ]
