# Generated by Django 5.0.6 on 2024-06-13 01:01

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('exams', '0004_alter_exam_added_by_alter_exam_description'),
        ('questions', '0004_question_skill_tags_alter_answer_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='skill_tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='core.SkillTagged', to='core.SkillTag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_questions', to='exams.exam'),
        ),
        migrations.AlterField(
            model_name='examquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_questions', to='questions.question'),
        ),
    ]
