# Generated by Django 5.0.6 on 2024-07-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_alter_userexam_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='retake',
            new_name='can_retake',
        ),
        migrations.RenameField(
            model_name='userexam',
            old_name='time_taken',
            new_name='time_given',
        ),
        migrations.RemoveField(
            model_name='examquestion',
            name='can_see_explanation',
        ),
        migrations.AddField(
            model_name='exam',
            name='can_see_explanation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userexam',
            name='status',
            field=models.IntegerField(choices=[(0, 'Not Started'), (1, 'In Progress'), (2, 'Finished')], default=0),
        ),
    ]
