# Generated by Django 5.0.6 on 2024-07-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_alter_examquestion_options_rename_title_exam_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
