# Generated by Django 5.0.6 on 2024-07-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0011_alter_exam_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='source',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='source_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
