# Generated by Django 5.0.6 on 2024-07-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0012_alter_exam_source_alter_exam_source_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
