# Generated by Django 5.0.6 on 2024-09-01 18:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('exams', '0015_remove_exam_unique_exam_source_id_alter_exam_source_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='exam',
            name='unique_exam_source_id',
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.UniqueConstraint(condition=models.Q(('source__isnull', False), models.Q(('source', ''), _negated=True), ('source_id__isnull', False), models.Q(('source_id', ''), _negated=True)), fields=('source', 'source_id'), name='unique_exam_source_id'),
        ),
    ]
