# Generated by Django 5.0.6 on 2024-09-16 08:35

import uuid
from django.db import migrations


def gen_uuid(apps, schema_editor):
    Exam = apps.get_model("exams", "Exam")
    for exam in Exam.objects.filter(uuid=None).only('id', 'uuid'):
        exam.uuid = uuid.uuid4()
        exam.save(update_fields=["uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0017_exam_uuid'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
