# Generated by Django 5.1.1 on 2024-09-22 11:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0019_auto_20240916_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='module',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('math', 'Math')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
    ]
