# Generated by Django 5.0.6 on 2024-09-17 03:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0019_auto_20240916_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
    ]
